### ISSUE TITLE
Solve the halting problem

### ISSUE THREAD

**Issue by hudson-ai** [notarealdeveloper/is_instance#3]
Hi, I want to be able to use is_instance to check function return types, e.g.

```python
def foo(*args):
   i = 0
   while True:
      i += 1
   return I

assert is_instance(foo, Callable[..., int])
```

**Comment by notarealdeveloper** [comment]
Solving the halting problem is a bit beyond the scope of the `is_instance` project, but it's a one-liner in [wnix](https://github.com/notarealdeveloper/wnix). I'd suggest you check out that project.

![issue-halting-problem](https://github.com/notarealdeveloper/is_instance/assets/28633680/d065ea7a-f982-4d2f-bdf7-f4ef2c69e21f)

**Comment by michen00** [comment]
I'm not sure if this is related to the halting problem, but I'd like to be able to use `is_instance` with subscripted generics. For instance, the following raises `TypeError: Subscripted generics cannot be used with class and instance checks` rather than returning `True`:

```python
>>> import is_instance
>>> from typing import Sequence
>>> is_instance("abc", Sequence[str])
```

The [snippet](https://github.com/notarealdeveloper/is_instance/issues/3#issue-1990572288) that @hudson-ai shared above should raise the same error.

**Comment by notarealdeveloper** [comment]
Ooh nice, I like this idea. Anyone have any ideas of how to implement it? I don't know much about subscripted generics but I'd be happy to add support for it if anyone knows how.

**Comment by notarealdeveloper** [comment]
@michen00 How's this? 

Not related to the halting problem (lol), but it should be enough to halt this github issue. 

Install `is_instance` version 0.0.7 from PyPI to get the new behavior.

<img width="586" alt="sequence" src="https://github.com/notarealdeveloper/is_instance/assets/28633680/cda2432f-1084-4d4c-bca8-6ef5368eac5c">
